# Generated by Django 5.1.4 on 2025-02-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasswordResetToken',
            new_name='PasswordResetOTP',
        ),
        migrations.RenameField(
            model_name='passwordresetotp',
            old_name='token',
            new_name='otp',
        ),
    ]
