# Generated by Django 5.1.4 on 2025-02-24 14:58

import user_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0002_user_coordinates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetotp",
            name="expires_at",
            field=models.DateTimeField(default=user_app.utils.set_otp_expire_date),
        ),
        migrations.AlterField(
            model_name="passwordresetotp",
            name="otp",
            field=models.CharField(
                default=user_app.utils.generate_otp, max_length=5, unique=True
            ),
        ),
    ]
