# Generated by Django 5.1.4 on 2025-02-18 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
    ]
